Created multisig account endpoint for post, retrieve and list
deep-ink-ventures/genesis-dao-service pull request #11
Opened 2023-07-03 08:36 UTC by pacifiquet

1. I created 3 endpoints for multisig account 
2. I added Testing for multisig endpoint view
3. I added multisig account unique key generator
4. I added new model for multisig account

2023-07-03 11:38 UTC, Shirku requested changes

2023-07-03 11:38 UTC, Shirku commented on core/models.py
> +class MultiSignature(TimestampableMixin):
as per this thread: https://deepinkventures.slack.com/archives/C04L9SJ0Y56/p1688381775700629
i think we need a different abstraction :thinking:

2023-07-03 11:40 UTC, Shirku commented
couple of the remarks are dated now because of the new abstraction we need https://deepinkventures.slack.com/archives/C04L9SJ0Y56/p1688381775700629 :/

2023-07-05 07:02 UTC, deepink-mas commented on core/migrations/__pycache__/0001_initial.cpython-311.pyc
maybe add *.pyc to .gitignore?

2023-07-05 15:59 UTC, deep-ink-ventures commented on core/migrations/__pycache__/0001_initial.cpython-311.pyc
Yeah, not single files.

2023-07-07 13:42 UTC, Shirku requested changes
we are getting somewhere :) found a couple more things tho

2023-07-07 13:42 UTC, Shirku commented on core/views.py
> +@method_decorator(swagger_auto_schema(operation_description="Retrieves A MultSigAccount."), "retrieve")
```suggestion
@method_decorator(swagger_auto_schema(operation_description="Retrieves A Multi Signature Account."), "retrieve")
```

2023-07-07 13:42 UTC, Shirku commented on core/views.py
> +@method_decorator(swagger_auto_schema(operation_description="Retrieves A MultSigAccount."), "retrieve")
doesn't hurt to be a bit more verbose

2023-07-07 13:42 UTC, Shirku commented on core/views.py
> +        return Response({"message": "signatories or threshold is missing"}, HTTP_400_BAD_REQUEST)
```suggestion
class MultiSignatureViewSet(ModelViewSet):
    @swagger_auto_schema(
        operation_id="Create Multi Signature Wallet",
        operation_description="Creating a Multi Signature Wallet",
        responses={201: openapi.Response("", serializers.MultiSignatureSerializer)},
    )
    def create(self, request, *args, **kwargs):
        from core.substrate import substrate_service

        if (signatories := request.data.get("signatories")) and (threshold := request.data.get("threshold")):
            try:
                multi_signature_account = models.MultiSignature.objects.create(
                    address=substrate_service.create_multisig_account(signatories=signatories, threshold=threshold),
                    signatories=signatories,
                    threshold=threshold,
                )
            except IntegrityError:
                return Response({"message": "Multi signature account already exists."}, HTTP_400_BAD_REQUEST)
            serializer = serializers.MultiSignatureSerializer(multi_signature_account)
            headers = self.get_success_headers(serializer.data)
            return Response(data=serializer.data, status=HTTP_201_CREATED, headers=headers)

        return Response({"message": "Signatories or threshold are missing."}, HTTP_400_BAD_REQUEST)
```

2023-07-07 13:42 UTC, Shirku commented on core/views.py
> +        return Response({"message": "signatories or threshold is missing"}, HTTP_400_BAD_REQUEST)
some improvements:
- line 337: it's a viewset not a view :P
- line 340: you don't need `many=False` explicitly
- more compact: line 345, line 348:
- -  in general if it doesn't hurt readability, shorter is better :P not a huge fan of declaring a var and only using it once in the next line
- - in 355 for example it makes sense to keep it like this, because putting it one expression actually makes it too long which results in 3 lines :P
- keep try...except blocks a little as possible. so just around the thing which can throw the exception. 
- line 355: add sucess_headers to keep in line w/ what django does

2023-07-07 13:42 UTC, Shirku commented on core/views.py
> +        return Response({"message": "signatories or threshold is missing"}, HTTP_400_BAD_REQUEST)
also:
- we a creating a multi sig acc for a dao. to be able to call this you need to be the current dao owner. therefore as i said be before this create func should live in the `DaoViewSet`
- - we can then make it a `ReadOnlyModelViewSet` and rm `http_method_names`
- this needs the permission class `IsDaoOwner`
- the created redoc is not correct. you can check it out by starting the server and checking http://127.0.0.1:8000/redoc/#operation/Create%20Multi%20Signature%20Wallet
- - it states that POST requires `address` which it doesn't. so we need 2 serializers in this case, one for the responses which we already have and one for the creation part of things

2023-07-07 13:42 UTC, Shirku commented on core/urls.py
> +    path(r"daos/<str:id>/multisig/", views.MultiSignatureView.as_view({"post": "create"}), name="core-multsig-create"),
this won't be needed if you move the create func to the `DaoViewSet` as mentioned in the `core/views` pr comments

2023-07-07 13:42 UTC, Shirku commented on core/serializers.py
> +    threshold = CharField(required=True)
shouldn't this be an integerfield?

2023-07-07 13:42 UTC, Shirku commented on core/tests/test_views.py
> +        self.assertEqual(response.data, expected_response)
not just this test but in general:

i always try to keep the tripple a / aaa pattern when writing tests and seprate these w/ newline. `arange, act, assert`. it's commonly used, not _just_ my OCD (:
so in this case:
```
    def test_get_multisig_wallet(self):
        address = "ETdJ5RGDZt65ZvEqFM4n2TLUTJxcoCeaeAJGGaiYfX7fxSH"
        models.MultiSignature.objects.create(address=address, signatories=self.get_signatories(), threshold=2)
        expected_response = {
            "address": "ETdJ5RGDZt65ZvEqFM4n2TLUTJxcoCeaeAJGGaiYfX7fxSH",
            "signatories": [
                "5HpG9w8EBLe5XCrbczpwq5TSXvedjrBGCwqxK1iQ7qUsSWFc",
                "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
            ],
            "threshold": "2",
        }

        response = self.client.get(reverse("core-multi-signature-detail", kwargs={"address": address}))

        self.assertEqual(response.status_code, HTTP_200_OK)
        self.assertEqual(response.data, expected_response)
```
not really a huge things but it really helps readability once you get used to it :pray:

2023-07-07 13:42 UTC, Shirku commented on core/tests/test_views.py
> +        self.assertIsNotNone(response)
as i said before: if there are things to assert, let's do it.
so same as above: `self.assertEqual(response, expected_response)`

2023-07-07 13:42 UTC, Shirku commented on core/tests/test_views.py
> +        self.assertEqual(response.status_code, HTTP_201_CREATED)
same here missing response.data assert

2023-07-07 13:42 UTC, Shirku commented on core/tests/test_views.py
> +        self.assertEqual(response[-1].status_code, HTTP_400_BAD_REQUEST)
hmm. i'd just call `substrate_service.create_multisig_account` once before api call to create the account.
then you can skip all that payloads, for loop, response[-1] jazz :P

2023-07-10 05:15 UTC, pacifiquet commented on core/views.py
> +        return Response({"message": "signatories or threshold is missing"}, HTTP_400_BAD_REQUEST)
self.get_success_headers(serializer.data)  is not available with ReadOnlyModelViewSet

2023-07-10 10:41 UTC, Shirku approved these changes
just some very minior things, you can merge directly after, no need for another review :)
great work!
![approved](https://github.com/deep-ink-ventures/genesis-dao-service/assets/50838850/d46ec9f2-61e8-4232-9afb-809e068c70e2)

2023-07-10 10:41 UTC, Shirku commented on core/views.py
> +        security=[{"Basic": []}],
```suggestion
        security=[{"Signature": []}],
```

2023-07-10 10:41 UTC, Shirku commented on core/views.py
> +
```suggestion
```

2023-07-10 10:41 UTC, Shirku commented on core/views.py
> +        return Response({"message": "signatories or threshold is missing"}, HTTP_400_BAD_REQUEST)
oh well

2023-07-10 10:41 UTC, Shirku commented on core/views.py
> +    def create_multsig(self, request, *args, **kwargs):
```suggestion
    @action(
        methods=["POST"], detail=True, url_path="multisig", permission_classes=[IsDAOOwner], authentication_classes=[]
    )
    def create_multisig(self, request, *args, **kwargs):
```

2023-07-10 10:44 UTC, Shirku commented
ah and please squash and merge and use a sorta meaningful msg

2023-07-10 12:08 UTC, merged