TICKETS #6-#7-#7: Created endpoints for multisig transactions and lis…
deep-ink-ventures/genesis-dao-service pull request #16
Opened 2023-07-13 08:06 UTC by pacifiquet

…ten to events

2023-07-14 11:18 UTC, Shirku requested changes
also please always link the ticket in the pr description if possible :P

2023-07-14 11:18 UTC, Shirku commented on core/tests/test_event_handler.py
> +        )
wtf?
```suggestion
        multisig_address = models.MultiSignature.objects.create(
            address=multisig_account, signatories=[signer_one, signer_two], threshold=2
        )
```

2023-07-14 11:18 UTC, Shirku commented on core/tests/test_event_handler.py
> +            self.create_multisig_cancelled_event_action(block__multisig_cancelled_event, dao, multisig_address)
i don't understand what's happening here. these should be 3 separate tests, or even better 1 using ddt (lots of examples around).
this fails for me if i run mutliple times, some objects are not cleaned up properly.

2023-07-14 11:18 UTC, Shirku commented on core/tests/test_models.py
> +        self.assertEqual(str(models.MultisigTransaction(status="PENDING")), "PENDING")
aside from the fact that this shouldn't be the `__str__` as mentioned in the models.py:
if there are enum values, we should use them.
`status=TransactionStatus.PENDING`

2023-07-14 11:18 UTC, Shirku commented on core/tests/test_substrate.py
> +        )
```suggestion
        multisig_account = self.substrate_service.create_multisig_account([keypair_bob, keypair_alice], 2)
        
        self.substrate_service.create_multisig_event(
            keypair=keypair_alice, multisig_account=multisig_account, value=1, wait_for_inclusion=True
        )
```

2023-07-14 11:18 UTC, Shirku commented on core/tests/test_substrate.py
> +        )
nl to separate (aaa)

2023-07-14 11:18 UTC, Shirku commented on core/tests/test_views.py
> +        self.assertEqual(modified_response_data, expected_response)
nl after response.
also this is a bit ugly you can use freezegun for this or mock time

2023-07-14 11:18 UTC, Shirku commented on core/tests/test_views.py
> +        self.assertEqual(modified_response_data, expected_response)
same for the other tests

2023-07-14 11:18 UTC, Shirku commented on core/tests/test_models.py
> +        self.assertEqual(str(models.MultisigTransaction(status="PENDING")), "PENDING")
this also applies to other tests e.g. views :P

2023-07-19 05:40 UTC, pacifiquet commented on core/models.py
> +    dao = models.ForeignKey(Dao, related_name="daos", on_delete=models.CASCADE)
in the ticket they mention we need to filter with dao or status

2023-07-19 05:41 UTC, pacifiquet commented on core/models.py
> +    cancelled_by = models.CharField(max_length=150, null=True)
approvers and last_approver mentioned in the ticket as well

2023-07-19 13:00 UTC, Shirku commented on core/event_handler.py
> +            )
rule of thumb: queries are slow. optimize them if possible. fetch stuff all at once.
this does a new query for each iteration of the for loop. move outside.
in general: the number of queries should not depend on the number of objects (unless we have to do pagination, which we don't here)
please adjust this everyone through this func and add coverage for it in tests.


also what is this? `call_hash__in=[new_event.get("call_hash")]`
why search in a sequence which you create from 1 entry?
`call_hash=new_event.get("call_hash")`

2023-07-19 13:02 UTC, Shirku commented on core/event_handler.py
> +                    transaction_instance.approvers = [new_event.get("approving")]
if we know things are always gonna be there we can directly access them e.g.: `new_event["approving"]`

2023-07-19 13:04 UTC, Shirku commented on core/event_handler.py
> +                    transaction_instance.status = models.TransactionStatus.PENDING
so first of all pending appears to be the default value so we don't need to set it.
2ndly do we really want to set a transaction back to pending?

2023-07-19 13:04 UTC, Shirku commented on core/event_handler.py
> +            else:
why else?
there might be some new, some old, no?

2023-07-19 13:05 UTC, Shirku commented on core/event_handler.py
> +                    dao=models.Dao.objects.filter(owner__address=new_event.get("multisig")).get(),
also move out of the loop.
why is there a `get()`?

2023-07-19 13:06 UTC, Shirku commented on core/event_handler.py
> +                    transaction_instance.approvers = [new_event.get("approving")]
please adjust everywhere where we know it's safe

2023-07-19 13:07 UTC, Shirku commented on core/event_handler.py
> +            transaction_to_update = []
names should be plural

2023-07-19 13:11 UTC, Shirku commented on core/event_handler.py
> +                if len(transaction_instance.approvers) == multi_signature.threshold:
`>=`, no?

2023-07-19 13:12 UTC, Shirku commented on core/event_handler.py
> +                transaction_instance.approvers.append(approval_event.get("approving"))
append? isn't this a list?

2023-07-19 13:13 UTC, Shirku commented on core/event_handler.py
> +            )
we could just update all Transactions at once in the end

2023-07-19 13:16 UTC, Shirku commented on core/substrate.py
> +        call_function: str,
just let the func take an `GenericCall` or smth :P

2023-07-19 13:17 UTC, Shirku commented on core/substrate.py
> +                    call_params={"dest": keypair.ss58_address, "value": value},
what is `dest`? leftover from the balance thing?

2023-07-19 13:19 UTC, Shirku commented on core/views.py
> +            try:
as i said before, please keep `try...except` as small as possible

2023-07-19 13:22 UTC, Shirku commented on core/views.py
> +                    ),
why do we create the hash? i thought it should come from FE? https://github.com/deep-ink-ventures/genesis-dao-service/issues/13
```
The first endpoint should store:
the original call data, and
the hash (as calculated by the frontend)
```

2023-07-19 13:24 UTC, Shirku commented on core/views.py
> +                return Response({"message": "Multisignature account or Dao not found."}, HTTP_400_BAD_REQUEST)
let's do these separately

2023-07-19 13:25 UTC, Shirku commented on core/views.py
> +        return Response({"message": "call_module, call_function or call_params are missing."}, HTTP_400_BAD_REQUEST)
let's keep following the return early paradigm:
```
if not call_params := request.data.get("call_params")....
        return Response({"message": "call_module, call_function or call_params are missing."}, HTTP_400_BAD_REQUEST)
```

2023-07-19 13:27 UTC, Shirku commented on core/views.py
> +    lookup_field = "pk"
that is the default

2023-07-21 11:09 UTC, pacifiquet commented on core/substrate.py
> +                    call_params={"dest": keypair.ss58_address, "value": value},
The "dest" key holds the destination address
i should pass it as param as welll

2023-08-17 17:41 UTC, merged